import Head from 'next/head'
import Axios from "axios";
import { useGlobalContext } from '../components/Context';
import UploadImage from '../components/UploadImage';
import MainTexts from '../components/MainTexts';



export default function Home({ data }) {
  const { user, error, isLoading } = useGlobalContext();


  return (
    <>
      <Head>
        <title>Mercik Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </Head>

      <MainTexts />
      {user && <UploadImage />}


    </>
  )
}
